#!/usr/bin/env python3
"""Fail-fast repository hygiene checks with no third-party dependencies."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = ROOT / "src/python_extensions/_version.py"

FORBIDDEN_DIR_NAMES = {
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "build",
    "dist",
}
FORBIDDEN_SUFFIXES = {".pyc", ".pyo"}
SECRET_PATTERNS = {
    "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "GitHub token": re.compile(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{20,}\b"),
    "PyPI token": re.compile(r"\bpypi-[A-Za-z0-9_-]{20,}\b"),
}
ACTIVE_TEXT_ROOTS = [
    ROOT / "src",
    ROOT / "tests",
    ROOT / "tools",
    ROOT / "docs",
    ROOT / ".github",
    ROOT / "benchmarks/scripts",
]
ACTIVE_TEXT_FILES = [
    ROOT / "README.md",
    ROOT / "CHANGELOG.md",
    ROOT / "CONTRIBUTING.md",
    ROOT / "SECURITY.md",
    ROOT / "CODE_OF_CONDUCT.md",
    ROOT / "GITHUB_SETUP.md",
    ROOT / "CITATION.cff",
    ROOT / "pyproject.toml",
    ROOT / "MANIFEST.in",
    ROOT / "benchmarks/README.md",
]

LOCAL_PATH_PATTERNS = (
    "/mnt/data/",
    "/home/oai/",
    "C:\\Users\\",
)


DOC_PLACEHOLDERS = (
    "<OWNER>",
    "<your-repository-url>",
    "your-repository-url",
)


def _version() -> str:
    match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', VERSION_FILE.read_text(encoding="utf-8"), re.M)
    if not match:
        raise RuntimeError("cannot read __version__")
    return match.group(1)


def _iter_active_text_files():
    seen: set[Path] = set()
    for path in ACTIVE_TEXT_FILES:
        if path.is_file() and path not in seen:
            seen.add(path)
            yield path
    for root in ACTIVE_TEXT_ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in {".py", ".md", ".toml", ".yml", ".yaml", ".txt", ".cff"} and path not in seen:
                seen.add(path)
                yield path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--allow-dirty-build-output", action="store_true")
    args = parser.parse_args()
    errors: list[str] = []
    warnings: list[str] = []

    version = _version()
    checks = {
        ROOT / "README.md": f"Version **{version}**",
        ROOT / "CHANGELOG.md": f"## {version}",
        ROOT / "CITATION.cff": f'version: "{version}"',
        ROOT / "SECURITY.md": f"Version **{version}** is the current supported release",
        ROOT / "GITHUB_SETUP.md": f"source version is `{version}`",
        ROOT / "CONTRIBUTING.md": f"current release is **{version}**",
        ROOT / "docs/ARCHITECTURE.md": f"Current documented release: **{version}**",
        ROOT / "docs/COMPREHENSIVE_GUIDE.md": f"`python_extensions` {version}",
        ROOT / "docs/COMPATIBILITY.md": f"Current supported release: **{version}**",
        ROOT / "docs/RELEASE_NOTES.md": f"## {version}",
        ROOT / "docs/RELEASING.md": f"v{version}",
        ROOT / "benchmarks/README.md": f"Current benchmark evidence release: **{version}**",
        ROOT / ".github/ISSUE_TEMPLATE/bug.yml": f'placeholder: "{version}"',
        ROOT / ".github/REPOSITORY_METADATA.md": f"**Current release:** `{version}`",
    }
    for path, needle in checks.items():
        text = path.read_text(encoding="utf-8")
        if needle not in text:
            errors.append(f"version drift: {path.relative_to(ROOT)} does not contain {needle!r}")

    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    for needle in ('name = "cpython-extensions"', 'requires-python = ">=3.13,<3.14"', 'license = "MPL-2.0"', 'bytecode>=0.17,<0.18', 'twine>=5,<7', 'trove-classifiers>=2026.6.1.19', 'Programming Language :: Python :: Implementation :: CPython', '[project.urls]', 'https://github.com/Karvp/cpython-extensions'):
        if needle not in pyproject:
            errors.append(f"pyproject invariant missing: {needle}")

    for path in ROOT.rglob("*"):
        rel = path.relative_to(ROOT)
        if ".git" in rel.parts:
            continue
        if path.is_dir() and (path.name in FORBIDDEN_DIR_NAMES or path.name.endswith(".egg-info")):
            if not args.allow_dirty_build_output:
                errors.append(f"generated directory present: {rel}")
        elif path.is_file() and path.suffix in FORBIDDEN_SUFFIXES:
            if not args.allow_dirty_build_output:
                errors.append(f"generated bytecode present: {rel}")

    for path in _iter_active_text_files():
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rel = path.relative_to(ROOT)
        if path.resolve() != Path(__file__).resolve():
            for local in LOCAL_PATH_PATTERNS:
                if local in text:
                    errors.append(f"machine-local path {local!r} in active file: {rel}")
        if path.suffix.lower() in {".md", ".txt", ".cff"}:
            for placeholder in DOC_PLACEHOLDERS:
                if placeholder in text:
                    errors.append(f"documentation placeholder {placeholder!r} in active file: {rel}")
            if re.search(r"[ \t]+$", text, re.M):
                errors.append(f"trailing whitespace in active documentation: {rel}")
            if "\n\n\n\n" in text:
                errors.append(f"excess blank lines in active documentation: {rel}")
        for label, pattern in SECRET_PATTERNS.items():
            if pattern.search(text):
                errors.append(f"possible {label} committed in: {rel}")


    markdown_link = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
    for path in _iter_active_text_files():
        if path.suffix.lower() != ".md":
            continue
        text = path.read_text(encoding="utf-8")
        for match in markdown_link.finditer(text):
            href = match.group(1)
            if href.startswith(("http://", "https://", "mailto:", "#")):
                continue
            target_text = href.split("#", 1)[0]
            if not target_text:
                continue
            target = (path.parent / target_text).resolve()
            if not target.exists():
                errors.append(
                    f"broken local markdown link in {path.relative_to(ROOT)}: {href}"
                )

    version_token = "V" + "".join(version.split("."))
    benchmark_evidence = ROOT / f"benchmarks/results/BENCHMARK_SWITCH_SCALING_{version_token}.json"
    if benchmark_evidence.is_file():
        try:
            benchmark = json.loads(benchmark_evidence.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            errors.append(f"cannot read switch benchmark evidence: {exc}")
        else:
            if benchmark.get("package_version") != version:
                errors.append("switch benchmark evidence package_version does not match release version")
            rows = {
                (row.get("key_kind"), row.get("size")): row
                for row in benchmark.get("rows", [])
                if isinstance(row, dict)
            }
            for key_kind in ("int", "str"):
                for size in (2, 4, 8, 16, 32, 64, 128, 256, 512, 1024):
                    if (key_kind, size) not in rows:
                        errors.append(f"switch benchmark evidence missing {key_kind}/{size} row")
            readme = (ROOT / "README.md").read_text(encoding="utf-8")
            int_1024 = rows.get(("int", 1024))
            str_1024 = rows.get(("str", 1024))
            if int_1024:
                speedup = f"{float(int_1024['speedup_vs_if_elif']):.2f}×"
                if speedup not in readme:
                    errors.append(f"README switch benchmark is not synchronized with evidence ({speedup})")
            if str_1024:
                speedup = f"{float(str_1024['speedup_vs_if_elif']):.2f}×"
                if speedup not in readme:
                    errors.append(f"README string benchmark is not synchronized with evidence ({speedup})")
    else:
        errors.append(f"current-release switch benchmark evidence is missing: {benchmark_evidence.relative_to(ROOT)}")

    for stem in ("BENCHMARK_EXTENSION_BENEFITS", "BENCHMARK_README_BASELINE"):
        evidence = ROOT / f"benchmarks/results/{stem}_{version_token}.json"
        if not evidence.is_file():
            errors.append(f"current-release benchmark evidence is missing: {evidence.relative_to(ROOT)}")
            continue
        try:
            payload = json.loads(evidence.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            errors.append(f"cannot read {evidence.relative_to(ROOT)}: {exc}")
            continue
        if payload.get("package_version") != version:
            errors.append(f"benchmark evidence package_version does not match release version: {evidence.relative_to(ROOT)}")

    license_text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    if not license_text.startswith("Mozilla Public License Version 2.0"):
        errors.append("LICENSE is not the canonical MPL 2.0 text")
    citation = (ROOT / "CITATION.cff").read_text(encoding="utf-8")
    if "license: MPL-2.0" not in citation:
        errors.append("CITATION.cff license metadata is not MPL-2.0")
    if 'repository-code: "https://github.com/Karvp/cpython-extensions"' not in citation:
        errors.append("CITATION.cff repository-code does not identify the canonical repository")

    guide = ROOT / "docs/COMPREHENSIVE_GUIDE.md"
    if not guide.is_file() or guide.stat().st_size < 10_000:
        errors.append("comprehensive guide missing or unexpectedly small")

    required = [
        ".github/workflows/ci.yml",
        ".github/workflows/stress.yml",
        ".github/workflows/codeql.yml",
        ".github/workflows/release.yml",
        ".github/dependabot.yml",
        "SECURITY.md",
        "tools/install_dependencies.py",
        "tools/check_metadata.py",
        ".github/scripts/publish_release.cjs",
        "CONTRIBUTING.md",
        "LICENSE",
        ".github/REPOSITORY_METADATA.md",
    ]
    for rel in required:
        if not (ROOT / rel).exists():
            errors.append(f"required repository file missing: {rel}")

    if '"Implementation :: CPython"' in pyproject:
        errors.append("invalid shortened CPython Trove classifier present")

    release_workflow = (ROOT / ".github/workflows/release.yml").read_text(encoding="utf-8")
    if 'python tools/install_dependencies.py' not in release_workflow:
        errors.append("release workflow must install dependency groups without installing the project")
    if '.[build' in release_workflow or '.[test' in release_workflow:
        errors.append("release workflow must not install local project extras before clean-tree validation")
    if 'packages-dir: dist/' in release_workflow:
        errors.append("PyPI publish directory must not include SHA256SUMS.txt or other non-distribution files")
    if 'packages-dir: pypi-dist/' not in release_workflow or 'cp dist/*.whl dist/*.tar.gz pypi-dist/' not in release_workflow:
        errors.append("release workflow must stage only wheel/sdist files for PyPI publishing")
    if 'actions/github-script@v9' not in release_workflow:
        errors.append("GitHub Release creation must use the API-driven github-script release step")
    if 'actions: read' not in release_workflow:
        errors.append("artifact-consuming release jobs must request actions: read explicitly")
    if "needs.build.outputs.channel == 'stable'" not in release_workflow:
        errors.append("PyPI publishing must be restricted to the exact stable release channel")
    if 'RELEASE_CHANNEL: ${{ needs.build.outputs.channel }}' not in release_workflow:
        errors.append("GitHub Release job must receive the validated release channel")
    clean_step = release_workflow.find("Check clean repository and tag version")
    dependency_step = release_workflow.find("Install declared release dependencies")
    if clean_step < 0 or dependency_step < 0 or clean_step > dependency_step:
        errors.append("release workflow must validate the clean tagged tree before installing dependencies")

    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"repository hygiene: PASS (version {version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
