#!/usr/bin/env python3
"""Fail-fast repository hygiene checks with no third-party dependencies."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = ROOT / "src/python_extensions/_version.py"

FORBIDDEN_DIR_NAMES = {
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "build",
    "dist",
}
FORBIDDEN_SUFFIXES = {".pyc", ".pyo"}
SECRET_PATTERNS = {
    "private key": re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "GitHub token": re.compile(r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{20,}\b"),
    "PyPI token": re.compile(r"\bpypi-[A-Za-z0-9_-]{20,}\b"),
}
ACTIVE_TEXT_ROOTS = [
    ROOT / "src",
    ROOT / "tests",
    ROOT / "tools",
    ROOT / "docs",
    ROOT / ".github",
    ROOT / "benchmarks/scripts",
]
ACTIVE_TEXT_FILES = [
    ROOT / "README.md",
    ROOT / "CHANGELOG.md",
    ROOT / "CONTRIBUTING.md",
    ROOT / "SECURITY.md",
    ROOT / "CODE_OF_CONDUCT.md",
    ROOT / "GITHUB_SETUP.md",
    ROOT / "CITATION.cff",
    ROOT / "pyproject.toml",
    ROOT / "MANIFEST.in",
    ROOT / "benchmarks/README.md",
]

LOCAL_PATH_PATTERNS = (
    "/mnt/data/",
    "/home/oai/",
    "C:\\Users\\",
)


def _version() -> str:
    match = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', VERSION_FILE.read_text(encoding="utf-8"), re.M)
    if not match:
        raise RuntimeError("cannot read __version__")
    return match.group(1)


def _iter_active_text_files():
    seen: set[Path] = set()
    for path in ACTIVE_TEXT_FILES:
        if path.is_file() and path not in seen:
            seen.add(path)
            yield path
    for root in ACTIVE_TEXT_ROOTS:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_file() and path.suffix.lower() in {".py", ".md", ".toml", ".yml", ".yaml", ".txt", ".cff"} and path not in seen:
                seen.add(path)
                yield path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--allow-dirty-build-output", action="store_true")
    args = parser.parse_args()
    errors: list[str] = []
    warnings: list[str] = []

    version = _version()
    checks = {
        ROOT / "README.md": f"Version **{version}**",
        ROOT / "CHANGELOG.md": f"## {version}",
        ROOT / "CITATION.cff": f'version: "{version}"',
    }
    for path, needle in checks.items():
        text = path.read_text(encoding="utf-8")
        if needle not in text:
            errors.append(f"version drift: {path.relative_to(ROOT)} does not contain {needle!r}")

    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    for needle in ('name = "cpython-extensions"', 'requires-python = ">=3.13,<3.14"', 'license = "MPL-2.0"', 'bytecode>=0.17,<0.18', 'twine>=5,<7'):
        if needle not in pyproject:
            errors.append(f"pyproject invariant missing: {needle}")

    for path in ROOT.rglob("*"):
        rel = path.relative_to(ROOT)
        if ".git" in rel.parts:
            continue
        if path.is_dir() and (path.name in FORBIDDEN_DIR_NAMES or path.name.endswith(".egg-info")):
            if not args.allow_dirty_build_output:
                errors.append(f"generated directory present: {rel}")
        elif path.is_file() and path.suffix in FORBIDDEN_SUFFIXES:
            if not args.allow_dirty_build_output:
                errors.append(f"generated bytecode present: {rel}")

    for path in _iter_active_text_files():
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rel = path.relative_to(ROOT)
        if path.resolve() != Path(__file__).resolve():
            for local in LOCAL_PATH_PATTERNS:
                if local in text:
                    errors.append(f"machine-local path {local!r} in active file: {rel}")
        for label, pattern in SECRET_PATTERNS.items():
            if pattern.search(text):
                errors.append(f"possible {label} committed in: {rel}")


    license_text = (ROOT / "LICENSE").read_text(encoding="utf-8")
    if not license_text.startswith("Mozilla Public License Version 2.0"):
        errors.append("LICENSE is not the canonical MPL 2.0 text")
    citation = (ROOT / "CITATION.cff").read_text(encoding="utf-8")
    if "license: MPL-2.0" not in citation:
        errors.append("CITATION.cff license metadata is not MPL-2.0")

    guide = ROOT / "docs/COMPREHENSIVE_GUIDE.md"
    if not guide.is_file() or guide.stat().st_size < 10_000:
        errors.append("comprehensive guide missing or unexpectedly small")

    required = [
        ".github/workflows/ci.yml",
        ".github/workflows/stress.yml",
        ".github/workflows/codeql.yml",
        ".github/workflows/release.yml",
        ".github/dependabot.yml",
        "SECURITY.md",
        "tools/install_dependencies.py",
        "CONTRIBUTING.md",
        "LICENSE",
        ".github/REPOSITORY_METADATA.md",
    ]
    for rel in required:
        if not (ROOT / rel).exists():
            errors.append(f"required repository file missing: {rel}")

    release_workflow = (ROOT / ".github/workflows/release.yml").read_text(encoding="utf-8")
    if 'python tools/install_dependencies.py' not in release_workflow:
        errors.append("release workflow must install dependency groups without installing the project")
    if '.[build' in release_workflow or '.[test' in release_workflow:
        errors.append("release workflow must not install local project extras before clean-tree validation")
    if 'packages-dir: dist/' in release_workflow:
        errors.append("PyPI publish directory must not include SHA256SUMS.txt or other non-distribution files")
    if 'packages-dir: pypi-dist/' not in release_workflow or 'cp dist/*.whl dist/*.tar.gz pypi-dist/' not in release_workflow:
        errors.append("release workflow must stage only wheel/sdist files for PyPI publishing")
    if '-R "$GITHUB_REPOSITORY"' not in release_workflow:
        errors.append("GitHub Release CLI calls must select the repository explicitly in the no-checkout release job")
    clean_step = release_workflow.find("Check clean repository and tag version")
    dependency_step = release_workflow.find("Install declared release dependencies")
    if clean_step < 0 or dependency_step < 0 or clean_step > dependency_step:
        errors.append("release workflow must validate the clean tagged tree before installing dependencies")

    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"repository hygiene: PASS (version {version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
